//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUnits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUnits()
        {
            this.AdminUnits1 = new HashSet<AdminUnits>();
            this.Organization = new HashSet<Organization>();
            this.LicenseRequest = new HashSet<LicenseRequest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int IdTypeadm { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsRayonCenter { get; set; }
        public string Name_ru { get; set; }
        public string Name_kg { get; set; }
        public string Description_kg { get; set; }
        public string Description_ru { get; set; }
        public string CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUnits> AdminUnits1 { get; set; }
        public virtual AdminUnits AdminUnits2 { get; set; }
        public virtual TypeAdminUnits TypeAdminUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization> Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseRequest> LicenseRequest { get; set; }
    }
}
