//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentInRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentInRequest()
        {
            this.MessageForSentDocument = new HashSet<MessageForSentDocument>();
        }
    
        public int Id { get; set; }
        public int Id_Request { get; set; }
        public int Id_Document { get; set; }
        public int Id_DocumentState { get; set; }
        public Nullable<int> Id_RequestElement { get; set; }
        public string Description { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual LicenseRequest LicenseRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageForSentDocument> MessageForSentDocument { get; set; }
        public virtual DocumentState DocumentState { get; set; }
        public virtual RequestElement RequestElement { get; set; }
    }
}
