//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LicenseRequest()
        {
            this.DocumentInRequest = new HashSet<DocumentInRequest>();
            this.LicenseRequestActivityType = new HashSet<LicenseRequestActivityType>();
            this.RequestStateHistory = new HashSet<RequestStateHistory>();
            this.Message = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string ClinicName { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> Id_Company { get; set; }
        public Nullable<int> Id_AdminUnit { get; set; }
        public Nullable<int> Id_RequestType { get; set; }
        public int Id_User { get; set; }
        public bool IsDraft { get; set; }
    
        public virtual AdminUnits AdminUnits { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentInRequest> DocumentInRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseRequestActivityType> LicenseRequestActivityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestStateHistory> RequestStateHistory { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual RequestType RequestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
    }
}
