//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseRequestActivityType
    {
        public int Id { get; set; }
        public int Id_Type { get; set; }
        public int Id_Request { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual LicenseRequest LicenseRequest { get; set; }
    }
}
