//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.MessageForSentDocument = new HashSet<MessageForSentDocument>();
            this.Message1 = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Parent { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public int Id_Request { get; set; }
        public Nullable<int> Id_QuestionType { get; set; }
        public int Id_AnswerWriter { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual LicenseRequest LicenseRequest { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageForSentDocument> MessageForSentDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
    }
}
