//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedlicenseEntities : DbContext
    {
        public MedlicenseEntities()
            : base("name=MedlicenseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<AdminUnits> AdminUnits { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<DocTemplForReqElemType> DocTemplForReqElemType { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Document_Format> Document_Format { get; set; }
        public virtual DbSet<DocumentInRequest> DocumentInRequest { get; set; }
        public virtual DbSet<DocumentState> DocumentState { get; set; }
        public virtual DbSet<LicenseRequest> LicenseRequest { get; set; }
        public virtual DbSet<LicenseRequestActivityType> LicenseRequestActivityType { get; set; }
        public virtual DbSet<LocalGoverment2> LocalGoverment2 { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MessageForSentDocument> MessageForSentDocument { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<OrganizationType> OrganizationType { get; set; }
        public virtual DbSet<QuestionType> QuestionType { get; set; }
        public virtual DbSet<RequestElement> RequestElement { get; set; }
        public virtual DbSet<RequestElementType> RequestElementType { get; set; }
        public virtual DbSet<RequestElemStructureType> RequestElemStructureType { get; set; }
        public virtual DbSet<RequestState> RequestState { get; set; }
        public virtual DbSet<RequestStateHistory> RequestStateHistory { get; set; }
        public virtual DbSet<RequestStep> RequestStep { get; set; }
        public virtual DbSet<RequestType> RequestType { get; set; }
        public virtual DbSet<SettlementType> SettlementType { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<TypeAdminUnits> TypeAdminUnits { get; set; }
    }
}
