//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.LicenseRequest = new HashSet<LicenseRequest>();
        }
    
        public int Id { get; set; }
        public string TIN { get; set; }
        public string NSCCode { get; set; }
        public string RegistrationNumber { get; set; }
        public int Id_Type { get; set; }
        public string Address { get; set; }
        public int Id_AdminUnit { get; set; }
        public string Name_ru { get; set; }
        public string Name_kg { get; set; }
        public string Description_kg { get; set; }
        public string Description_ru { get; set; }
        public string CODE { get; set; }
    
        public virtual AdminUnits AdminUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseRequest> LicenseRequest { get; set; }
        public virtual OrganizationType OrganizationType { get; set; }
    }
}
