//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestStep()
        {
            this.RequestStep1 = new HashSet<RequestStep>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Parent { get; set; }
        public string Name_ru { get; set; }
        public string Name_kg { get; set; }
        public string Description_ru { get; set; }
        public string Description_kg { get; set; }
        public string CODE { get; set; }
        public string Url { get; set; }
        public string ActiveImageUrl { get; set; }
        public string DiabledImageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestStep> RequestStep1 { get; set; }
        public virtual RequestStep RequestStep2 { get; set; }
    }
}
